spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: serverb #指定应用名称
server:
  port: 10002 #指定该Eureka实例的端口号:
eureka:
  instance:
    prefer-ip-address: true #是否显示主机的ip
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} #在Eureka服务端界面的status一栏显示ip:port的形式
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:10000/eureka/ #指定Eureka服务端地址
